baseURL: "https://jnsgr.uk"

defaultContentLanguage: en

enableRobotsTXT: true
pagination:
  pagerSize: 15

summaryLength: 0

outputs:
  home:
    - HTML
    - RSS
    - JSON

frontmatter:
  date:
    - ":filename"
    - ":default"

permalinks:
  posts: /:year/:month/:slug/

enableGitInfo: true
