main:
  - name: Blog
    pageRef: posts
    weight: 10

  - name: CV
    pageRef: cv
    weight: 20

  - name: Meta
    pageRef: colophon
    weight: 30

  - identifier: "appearance"
    weight: 99
    params:
      action: "appearance"
      icon: "moon"
