colorScheme: slate
defaultAppearance: light
autoSwitchAppearance: true

enableSearch: true
enableCodeCopy: true
enableImageLazyLoading: true
enableImageWebp: true

fingerprintAlgorithm: sha256

header:
  layout: hybrid
  showTitle: true
  logo: img/logo.jpg

footer:
  showCopyright: false
  showThemeAttribution: false
  showAppearanceSwitcher: false
  showScrollToTop: true

homepage:
  layout: profile
  showRecent: false

article:
  showDate: true
  showDateUpdated: false
  showAuthor: true
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: false
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: false
  showWordCount: true
  showComments: false

list:
  showBreadcrumbs: true
  showSummary: true
  showTableOfContents: false
  showTaxonomies: false
  groupByYear: true
  paginationWidth: 1

sitemap:
  excludedKinds:
    - taxonomy
    - term

taxonomy:
  showTermCount: true
