name: Fly Deploy
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build rock
        uses: canonical/craft-actions/rockcraft-pack@main

      - name: Upload container to ghcr.io
        run: |
          ROCK=$(ls *.rock)
          TAG=$(git rev-parse --short HEAD)
          sudo skopeo copy \
            oci-archive:${ROCK} \
            docker-daemon:ghcr.io/jnsgruk/jnsgr.uk:${TAG}
          docker push ghcr.io/jnsgruk/jnsgr.uk:${TAG}

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy -i "ghcr.io/jnsgruk/jnsgr.uk:$(git rev-parse --short HEAD)"
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_API_TOKEN }}
